apiVersion: v1
kind: Secret
metadata:
  name: bsecret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: mysql
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_DATASOURCE_URL: jdbc:mysql://dbservice:3306/db
